name: Node.js CI

on:
  push:
    branches:
      - live_server

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Preserve uploads directory
        run: |
          mkdir -p /tmp/uploads_backup
          tar -czf /tmp/uploads_backup/uploads_backup.tar.gz uploads

      - name: Verify backup file creation
        run: |
          if [ -f /tmp/uploads_backup/uploads_backup.tar.gz ]; then
            echo "Backup file created successfully.";
          else
            echo "Backup file creation failed.";
            exit 1;
          fi

      - uses: actions/checkout@v4

      - name: Restore uploads directory
        run: |
          if [ -f /tmp/uploads_backup/uploads_backup.tar.gz ]; then
            tar -xzf /tmp/uploads_backup/uploads_backup.tar.gz;
            echo "Uploads directory restored successfully.";
            rm /tmp/uploads_backup/uploads_backup.tar.gz;
          else
            echo "Uploads backup file not found. Restore failed.";
            exit 1;
          fi

      - name: Clean up all backup files
        run: |
          find / -name uploads_backup.tar.gz -exec rm -f {} \;
          echo "All backup files removed."

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - run: npm ci
      - run: npm update
      - run: pm2 restart server
